version: '2.13.6'
services:
  ql:
    image: whyour/qinglong:latest
    container_name: ql
    restart: always
    volumes:
       - /qinglong/ql/config:/ql/config
       - /qinglong/ql/scripts:/ql/scripts
       - /qinglong/ql/repo:/ql/repo
       - /qinglong/ql/log:/ql/log
       - /qinglong/ql/db:/ql/db
       - /qinglong/ql/jbot:/ql/jbot
       - /qinglong/ql/raw:/ql/raw
    ports:
       - 5700:5700
